:linkattrs:
:source-highlighter: rouge


==== simpldate(schedule meetings) ====

=== Overview ===


==== The main aspects ====

* Process (with sub-process,message events and mail service task)
* Camel (creating a rpc api, showing how camel and activiti playing together)
* Form (embed in website)
* Webapp (Basic staffolding)


Main character: In this process, no usertasks will be used.
That's not possible, because an unknown number of participants are involved,
which also no users in simpl4 are.
Therefore the used Forms are designed as web pages.

* InitiateForm(initiate.form) starts the process.
* The voting page communicates with the process via rpc (final a message is sent to the  process)

--
[role=border]
image::http://simpldate.ms123.org/repo/simpldate/web/images/simpldate_overview.svg[align="center", scaledWidth=50%]
--

=== RPC ===


The application requires four rpc`s to interact with the process at the moment.
The fourth, finish the  process is not ready.
The Camel component "workflow" implements the  "rpc's".

* Starts the process.
* Messageevents are sent to the processs.
* Read variables(state) from the process.

--
[role=border]
image::http://simpldate.ms123.org/repo/simpldate/web/images/camel.svg[align="center"]
--

=== WEB ===

The web pages are implemented as  html5 customelements.

* simpldate-initiate
* simpldate-vote
